# Generated by Django 4.2.1 on 2023-06-07 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="sender",
        ),
    ]
