# Generated by Django 4.2.1 on 2023-06-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_remove_chatmessage_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="session_id",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
